version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: sveltekit:latest
    container_name: sveltekit-prod
    restart: unless-stopped
    ports:
      - "3002:3000"