version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: sveltekit:dev-latest
    container_name: sveltekit-dev
    restart: unless-stopped
    ports:
      - "3001:3000"