name: Development Deployment

on:
  pull_request:
    types: [closed]
    branches:
      - development
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    environment: development
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      #- name: Build Docker image
      #  run: docker buildx build -t svelte-app:${{ github.sha }} -f Dockerfile.dev .
      - name: Deploy to development server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/svelte-dev
            git pull origin development
            echo "${{ secrets.ENV_FILE }}" > .env
            docker compose build
            docker compose up -d
